name: 'Sanity checks'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  shellcheck:
    name: 'HTML tidy'
    strategy:
      fail-fast: false
      # Run on linux and macos
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Install tidy on Ubuntu'
        run: |
          sudo apt update
          sudo apt install tidy -y
          tidy --version
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      - name: "Run HTML tidy"
        run: |
          set -euxo pipefail
          cd ${{ github.workspace }}/
          for f in $(find . -type f -name "*.html"); do
            if file "$f" | grep "HTML" &>/dev/null; then
              tidy "$f"
            fi
          done
